fckeditor.basePath=/webadmin/fckeditor
connector.userFilesPath=/images
connector.resourceType.image.path=/
connector.resourceType.file.path=/
connector.resourceType.flash.path=/
connector.resourceType.media.path=/